apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: test-annotations-lbhf
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: test-annotations-lbhf
    app.kubernetes.io/part-of: build-suite-test-application-gdqo
  name: test-annotations-lbhf
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: my-nginx
      app.kubernetes.io/instance: test-annotations-lbhf
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: my-nginx
        app.kubernetes.io/instance: test-annotations-lbhf
    spec:
      containers:
      - image: quay.io/tnevrlka-test/build-e2e-vwum-tenant/build-suite-test-application-gdqo/test-annotations-lbhf@sha256:d6be3f169ebd1fe97f0613773c79138748b0e0b431d1800f65f1ef79338440f1
        name: my-nginx
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        - containerPort: 8081
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
